name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
         - name: Checkout
           uses: actions/checkout@v3
         - name: Install Dependencies
           run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
         - name: Lint with flake8
           run: |
            flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
         - name: Run unit tests with pytests
           run:  pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing
         - name: Scan for vulnerabilities with Bandit
           run: |
            python -m pip install bandit
            bandit -r src
